//! Mutable state shared between Obscura's host and the extension's JS realm.
//!
//! The host side (this crate) provides:
//! - storage areas (`chrome.storage.local`) backed by an in-memory JSON map
//! - registered listeners for `chrome.webRequest.*`, `chrome.runtime.onMessage`
//! - per-tab synthesised state (`tabs.query` etc. are answered from here)
//! - a transient outbox of "messages from background to content scripts"
//!
//! All listener bodies are JSON-encoded source strings; we don't execute
//! them here. `obscura-js` reaches in, finds listeners that match a URL,
//! and runs them in V8.
//!
//! No `unsafe`, no `tokio` dependency on purpose — this is a plain Rust
//! data layer. The async / V8 plumbing lives in the consumer crates.

use std::sync::{Mutex, RwLock};

use serde_json::Value;

/// `chrome.storage.local` / `chrome.storage.sync` / `chrome.storage.session`.
/// Obscura collapses all three to the same in-memory map keyed by area
/// name. Most real-world extensions only write to `.local`.
#[derive(Debug, Default)]
pub struct StorageArea {
    inner: RwLock<serde_json::Map<String, Value>>,
}

impl StorageArea {
    pub fn get(&self, key: &str) -> Option<Value> {
        self.inner.read().unwrap().get(key).cloned()
    }

    pub fn get_many(&self, keys: &[String]) -> serde_json::Map<String, Value> {
        let g = self.inner.read().unwrap();
        let mut out = serde_json::Map::new();
        for k in keys {
            if let Some(v) = g.get(k) {
                out.insert(k.clone(), v.clone());
            }
        }
        out
    }

    pub fn get_all(&self) -> serde_json::Map<String, Value> {
        self.inner.read().unwrap().clone()
    }

    pub fn set(&self, items: serde_json::Map<String, Value>) {
        let mut g = self.inner.write().unwrap();
        for (k, v) in items {
            g.insert(k, v);
        }
    }

    pub fn remove(&self, keys: &[String]) {
        let mut g = self.inner.write().unwrap();
        for k in keys {
            g.remove(k);
        }
    }

    pub fn clear(&self) {
        self.inner.write().unwrap().clear();
    }
}

/// One registered `chrome.webRequest.*` listener.
#[derive(Debug, Clone)]
pub struct WebRequestListener {
    pub event: WebRequestEvent,
    /// Listener id. Generated by the host so V8 can identify callbacks.
    pub id: u64,
    /// `urls`: match patterns the listener cares about. Empty = all URLs.
    pub url_patterns: Vec<String>,
    /// `types`: resource types (`main_frame`, `xmlhttprequest`, ...). Empty = all.
    pub types: Vec<String>,
    /// `extraInfoSpec`: includes `blocking`, `responseHeaders`, etc.
    pub extra: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WebRequestEvent {
    OnBeforeRequest,
    OnBeforeSendHeaders,
    OnHeadersReceived,
}

impl WebRequestEvent {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "onBeforeRequest" => Some(Self::OnBeforeRequest),
            "onBeforeSendHeaders" => Some(Self::OnBeforeSendHeaders),
            "onHeadersReceived" => Some(Self::OnHeadersReceived),
            _ => None,
        }
    }
}

/// In-process shared extension state. Wrapped in `Arc` by the host.
#[derive(Debug, Default)]
pub struct ExtensionState {
    pub storage_local: StorageArea,
    pub storage_sync: StorageArea,
    pub storage_session: StorageArea,
    /// All registered webRequest listeners. The id is the index + 1.
    listeners: RwLock<Vec<WebRequestListener>>,
    next_listener_id: Mutex<u64>,
    /// Set of paths/URL substrings that have been declared blocked by
    /// `declarativeNetRequest.updateSessionRules` actions. We extract just
    /// the urlFilter / regexFilter for the block action and treat it as a
    /// substring/regex match list. This is a deliberate shortcut for the
    /// common case where extensions register the same intent twice — once
    /// as a webRequest listener (MV2) and once as a DNR rule (MV3) — and
    /// we want the lighter-weight path to win.
    dnr_block_substrings: RwLock<Vec<String>>,
}

impl ExtensionState {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn register_listener(&self, mut l: WebRequestListener) -> u64 {
        let mut id_guard = self.next_listener_id.lock().unwrap();
        *id_guard += 1;
        l.id = *id_guard;
        let id = l.id;
        self.listeners.write().unwrap().push(l);
        id
    }

    pub fn remove_listener(&self, id: u64) {
        self.listeners.write().unwrap().retain(|l| l.id != id);
    }

    pub fn listeners_for(&self, event: WebRequestEvent) -> Vec<WebRequestListener> {
        self.listeners
            .read()
            .unwrap()
            .iter()
            .filter(|l| l.event == event)
            .cloned()
            .collect()
    }

    pub fn add_dnr_block(&self, substring: String) {
        self.dnr_block_substrings.write().unwrap().push(substring);
    }

    pub fn dnr_blocks(&self) -> Vec<String> {
        self.dnr_block_substrings.read().unwrap().clone()
    }
}
